/*
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.salesforce.marketingcloud.javasdk.model.Campaign;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GetAllCampaignsResponse
 */

public class GetAllCampaignsResponse {
  @SerializedName("items")
  private List<Campaign> items = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  public GetAllCampaignsResponse items(List<Campaign> items) {
    this.items = items;
    return this;
  }

  public GetAllCampaignsResponse addItemsItem(Campaign itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<Campaign>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @Valid
  @ApiModelProperty(value = "")
  public List<Campaign> getItems() {
    return items;
  }

  public void setItems(List<Campaign> items) {
    this.items = items;
  }

  public GetAllCampaignsResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of pages
   * @return count
  **/
  @ApiModelProperty(value = "Number of pages")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public GetAllCampaignsResponse page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Page number to return.
   * @return page
  **/
  @ApiModelProperty(value = "Page number to return.")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public GetAllCampaignsResponse pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Number of campaigns, which are array elements, to return per paged response.
   * @return pageSize
  **/
  @ApiModelProperty(value = "Number of campaigns, which are array elements, to return per paged response.")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAllCampaignsResponse getAllCampaignsResponse = (GetAllCampaignsResponse) o;
    return Objects.equals(this.items, getAllCampaignsResponse.items) &&
        Objects.equals(this.count, getAllCampaignsResponse.count) &&
        Objects.equals(this.page, getAllCampaignsResponse.page) &&
        Objects.equals(this.pageSize, getAllCampaignsResponse.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, count, page, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAllCampaignsResponse {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

