/*
 * NOTE: This class is auto generated by the clientgenerator program.
 * Do not edit the class manually.
 */


package com.github.salesforce.marketingcloud.javasdk.api;

import com.github.salesforce.marketingcloud.javasdk.exception.EnvironmentVariableNotSetException;
import com.github.salesforce.marketingcloud.javasdk.infrastructure.EnvVariableName;
import com.github.salesforce.marketingcloud.javasdk.infrastructure.EnvironmentConfigProvider;

public class Client {
    private final String authBaseUrl;
    private final String clientId;
    private final String clientSecret;
    private final String accountId;
    private final String scope;

    public Client() throws EnvironmentVariableNotSetException {
        EnvironmentConfigProvider configProvider = new EnvironmentConfigProvider();
        this.authBaseUrl = configProvider.get(EnvVariableName.AUTH_BASE_URL);
        this.clientId = configProvider.get(EnvVariableName.CLIENT_ID);
        this.clientSecret = configProvider.get(EnvVariableName.CLIENT_SECRET);
        this.accountId = configProvider.get(EnvVariableName.ACCOUNT_ID);
        this.scope = configProvider.get(EnvVariableName.SCOPE, false);
    }

    public Client(String authBaseUrl, String clientId, String clientSecret, String accountId, String scope) {
        this.authBaseUrl = authBaseUrl;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.accountId = accountId;
        this.scope = scope;
    }

    private AssetApi assetApi;

    public AssetApi getAssetApi() {
        if(assetApi == null)
        {
            assetApi = new AssetApi(authBaseUrl, clientId, clientSecret, accountId, scope);
        }
        return assetApi;
    }

    private CampaignApi campaignApi;

    public CampaignApi getCampaignApi() {
        if(campaignApi == null)
        {
            campaignApi = new CampaignApi(authBaseUrl, clientId, clientSecret, accountId, scope);
        }
        return campaignApi;
    }

    private TransactionalMessagingApi transactionalMessagingApi;

    public TransactionalMessagingApi getTransactionalMessagingApi() {
        if(transactionalMessagingApi == null)
        {
            transactionalMessagingApi = new TransactionalMessagingApi(authBaseUrl, clientId, clientSecret, accountId, scope);
        }
        return transactionalMessagingApi;
    }


}